//TODO: Autogenerate me
#include "file_resource_id_enums.h"

/*
 * The third field is where each file sits in the cartridge. On the console the
 * linker filled it in, because ob_seg.s .incbin'd every one of these files out
 * of an extracted ROM. No game data ships with the PC port, so there is
 * nothing to .incbin and none of those symbols exist -- the addresses are
 * written in at startup instead, from the ROM layout recorded in
 * scripts/filelist.u.csv. See port/include/obseg.h.
 *
 * Zero is not a placeholder the game will trip over: it already reads a zero
 * address as "this file is not in the cartridge" and takes another path.
 *
 * Without GEPC this expands to exactly the tokens that were here before.
 */
#ifdef GEPC
#  define OBSEG_ADDR(sym) 0
#else
#  define OBSEG_ADDR(sym) &sym
#endif

struct fileentry file_resource_table[] = {
    {NULLFILE, "", 0},
    {BG_SEV_ALL_P, "bg/bg_sev_all_p.seg", OBSEG_ADDR(bg_sev_all_p_seg)},
    {BG_SILO_ALL_P, "bg/bg_silo_all_p.seg", OBSEG_ADDR(bg_silo_all_p_seg)},
    {BG_STAT_ALL_P, "bg/bg_stat_all_p.seg", OBSEG_ADDR(bg_stat_all_p_seg)},
    {BG_AREC_ALL_P, "bg/bg_arec_all_p.seg", OBSEG_ADDR(bg_arec_all_p_seg)},
    {BG_ARCH_ALL_P, "bg/bg_arch_all_p.seg", OBSEG_ADDR(bg_arch_all_p_seg)},
    {BG_TRA_ALL_P, "bg/bg_tra_all_p.seg", OBSEG_ADDR(bg_tra_all_p_seg)},
    {BG_DEST_ALL_P, "bg/bg_dest_all_p.seg", OBSEG_ADDR(bg_dest_all_p_seg)},
    {BG_SEVB_ALL_P, "bg/bg_sevb_all_p.seg", OBSEG_ADDR(bg_sevb_all_p_seg)},
    {BG_AZT_ALL_P, "bg/bg_azt_all_p.seg", OBSEG_ADDR(bg_azt_all_p_seg)},
    {BG_PETE_ALL_P, "bg/bg_pete_all_p.seg", OBSEG_ADDR(bg_pete_all_p_seg)},
    {BG_DEPO_ALL_P, "bg/bg_depo_all_p.seg", OBSEG_ADDR(bg_depo_all_p_seg)},
    {BG_REF_ALL_P, "bg/bg_ref_all_p.seg", OBSEG_ADDR(bg_ref_all_p_seg)},
    {BG_CRYP_ALL_P, "bg/bg_cryp_all_p.seg", OBSEG_ADDR(bg_cryp_all_p_seg)},
    {BG_DAM_ALL_P, "bg/bg_dam_all_p.seg", OBSEG_ADDR(bg_dam_all_p_seg)},
    {BG_ARK_ALL_P, "bg/bg_ark_all_p.seg", OBSEG_ADDR(bg_ark_all_p_seg)},
    {BG_RUN_ALL_P, "bg/bg_run_all_p.seg", OBSEG_ADDR(bg_run_all_p_seg)},
    {BG_SEVX_ALL_P, "bg/bg_sevx_all_p.seg", OBSEG_ADDR(bg_sevx_all_p_seg)},
    {BG_JUN_ALL_P, "bg/bg_jun_all_p.seg", OBSEG_ADDR(bg_jun_all_p_seg)},
    {BG_DISH_ALL_P, "bg/bg_dish_all_p.seg", OBSEG_ADDR(bg_dish_all_p_seg)},
    {BG_CAVE_ALL_P, "bg/bg_cave_all_p.seg", OBSEG_ADDR(bg_cave_all_p_seg)},
    {BG_CAT_ALL_P, "bg/bg_cat_all_p.seg", OBSEG_ADDR(bg_cat_all_p_seg)},
    {BG_CRAD_ALL_P, "bg/bg_crad_all_p.seg", OBSEG_ADDR(bg_crad_all_p_seg)},
    {BG_SHO_ALL_P, "bg/bg_sho_all_p.seg", OBSEG_ADDR(bg_sho_all_p_seg)},
    {BG_ELD_ALL_P, "bg/bg_eld_all_p.seg", OBSEG_ADDR(bg_imp_all_p_seg)},
    {BG_IMP_ALL_P, "bg/bg_imp_all_p.seg", OBSEG_ADDR(bg_imp_all_p_seg)},
    {BG_ASH_ALL_P, "bg/bg_ash_all_p.seg", OBSEG_ADDR(bg_imp_all_p_seg)},
    {BG_LUE_ALL_P, "bg/bg_lue_all_p.seg", OBSEG_ADDR(bg_imp_all_p_seg)},
    {BG_AME_ALL_P, "bg/bg_ame_all_p.seg", OBSEG_ADDR(bg_imp_all_p_seg)},
    {BG_RIT_ALL_P, "bg/bg_rit_all_p.seg", OBSEG_ADDR(bg_rit_all_p_seg)},
    {BG_OAT_ALL_P, "bg/bg_oat_all_p.seg", OBSEG_ADDR(bg_oat_all_p_seg)},
    {BG_EAR_ALL_P, "bg/bg_ear_all_p.seg", OBSEG_ADDR(bg_ear_all_p_seg)},
    {BG_LEE_ALL_P, "bg/bg_lee_all_p.seg", OBSEG_ADDR(bg_lee_all_p_seg)},
    {BG_LIP_ALL_P, "bg/bg_lip_all_p.seg", OBSEG_ADDR(bg_lip_all_p_seg)},
    {BG_LEN_ALL_P, "bg/bg_len_all_p.seg", OBSEG_ADDR(bg_len_all_p_seg)},
    {BG_WAX_ALL_P, "bg/bg_wax_all_p.seg", OBSEG_ADDR(bg_wax_all_p_seg)},
    {BG_PAM_ALL_P, "bg/bg_pam_all_p.seg", OBSEG_ADDR(bg_pam_all_p_seg)},

    {ARMOURGUARD, "CarmourguardZ", OBSEG_ADDR(CarmourguardZ)},
    {BARONSAMEDI, "CbaronsamediZ", OBSEG_ADDR(CbaronsamediZ)},
    {BLUECAMGUARD, "CbluecamguardZ", OBSEG_ADDR(CbluecamguardZ)},
    {BLUEMAN, "CbluemanZ", OBSEG_ADDR(CbluemanZ)},
    {BLUEWOMAN, "CbluewomanZ", OBSEG_ADDR(CbluewomanZ)},
    {BOILERBOND, "CboilerbondZ", OBSEG_ADDR(CboilerbondZ)},
    {BOILERTREV, "CboilertrevZ", OBSEG_ADDR(CboilertrevZ)},
    {BORIS, "CborisZ", OBSEG_ADDR(CborisZ)},
    {CAMGUARD, "CcamguardZ", OBSEG_ADDR(CcamguardZ)},
    {CARDIMAN, "CcardimanZ", OBSEG_ADDR(CcardimanZ)},
    {CHECKMAN, "CcheckmanZ", OBSEG_ADDR(CcheckmanZ)},
    {COMMGUARD, "CcommguardZ", OBSEG_ADDR(CcommguardZ)},
    {DJBOND, "CdjbondZ", OBSEG_ADDR(CdjbondZ)},
    {FATTECHWOMAN, "CfattechwomanZ", OBSEG_ADDR(CfattechwomanZ)},
    {GREATGUARD2, "Cgreatguard2Z", OBSEG_ADDR(Cgreatguard2Z)},
    {GREATGUARD, "CgreatguardZ", OBSEG_ADDR(CgreatguardZ)},
    {GREYGUARD, "CgreyguardZ", OBSEG_ADDR(CgreyguardZ)},
    {GREYMAN, "CgreymanZ", OBSEG_ADDR(CgreymanZ)},
    {HEADALAN, "CheadalanZ", OBSEG_ADDR(CheadalanZ)},
    {HEADB, "CheadbZ", OBSEG_ADDR(CheadbZ)},
    {HEADBALACLAVA, "CheadbalaclavaZ", OBSEG_ADDR(CheadbalaclavaZ)},
    {HEADBIKE, "CheadbikeZ", OBSEG_ADDR(CheadbikeZ)},
    {HEADBROSNAN, "CheadbrosnanZ", OBSEG_ADDR(CheadbrosnanZ)},
    {HEADBROSNANBOILER, "CheadbrosnanboilerZ", OBSEG_ADDR(CheadbrosnanboilerZ)},
    {HEADBROSNANSNOW, "CheadbrosnansnowZ", OBSEG_ADDR(CheadbrosnansnowZ)},
    {HEADBROSNANSUIT, "CheadbrosnansuitZ", OBSEG_ADDR(CheadbrosnansuitZ)},
    {HEADBROSNANTIMBER, "CheadbrosnantimberZ", OBSEG_ADDR(CheadbrosnantimberZ)},
    {HEADCHRIS, "CheadchrisZ", OBSEG_ADDR(CheadchrisZ)},
    {HEADDAVE, "CheaddaveZ", OBSEG_ADDR(CheaddaveZ)},
    {HEADDES, "CheaddesZ", OBSEG_ADDR(CheaddesZ)},
    {HEADDUNCAN, "CheadduncanZ", OBSEG_ADDR(CheadduncanZ)},
    {HEADDWAYNE, "CheaddwayneZ", OBSEG_ADDR(CheaddwayneZ)},
    {HEADGRAHAM, "CheadgrahamZ", OBSEG_ADDR(CheadgrahamZ)},
    {HEADGRANT, "CheadgrantZ", OBSEG_ADDR(CheadgrantZ)},
    {HEADJIM, "CheadjimZ", OBSEG_ADDR(CheadjimZ)},
    {HEADJOE2, "Cheadjoe2Z", OBSEG_ADDR(Cheadjoe2Z)},
    {HEADJOE, "CheadjoeZ", OBSEG_ADDR(CheadjoeZ)},
    {HEADJOEL, "CheadjoelZ", OBSEG_ADDR(CheadjoelZ)},
    {HEADKARL, "CheadkarlZ", OBSEG_ADDR(CheadkarlZ)},
    {HEADKEN, "CheadkenZ", OBSEG_ADDR(CheadkenZ)},
    {HEADLEE, "CheadleeZ", OBSEG_ADDR(CheadleeZ)},
    {HEADMANDY, "CheadmandyZ", OBSEG_ADDR(CheadmandyZ)},
    {HEADMARION, "CheadmarionZ", OBSEG_ADDR(CheadmarionZ)},
    {HEADMARK, "CheadmarkZ", OBSEG_ADDR(CheadmarkZ)},
    {HEADMARTIN, "CheadmartinZ", OBSEG_ADDR(CheadmartinZ)},
    {HEADMISHKIN, "CheadmishkinZ", OBSEG_ADDR(CheadmishkinZ)},
    {HEADNEIL, "CheadneilZ", OBSEG_ADDR(CheadneilZ)},
    {HEADPETE, "CheadpeteZ", OBSEG_ADDR(CheadpeteZ)},
    {HEADROBIN, "CheadrobinZ", OBSEG_ADDR(CheadrobinZ)},
    {HEADSALLY, "CheadsallyZ", OBSEG_ADDR(CheadsallyZ)},
    {HEADSCOTT, "CheadscottZ", OBSEG_ADDR(CheadscottZ)},
    {HEADSHAUN, "CheadshaunZ", OBSEG_ADDR(CheadshaunZ)},
    {HEADSTEVEE, "CheadsteveeZ", OBSEG_ADDR(CheadsteveeZ)},
    {HEADSTEVEH, "CheadstevehZ", OBSEG_ADDR(CheadstevehZ)},
    {HEADVIVIEN, "CheadvivienZ", OBSEG_ADDR(CheadvivienZ)},
    {JAWS, "CjawsZ", OBSEG_ADDR(CjawsZ)},
    {JEANWOMAN, "CjeanwomanZ", OBSEG_ADDR(CjeanwomanZ)},
    {MAYDAY, "CmaydayZ", OBSEG_ADDR(CmaydayZ)},
    {MOONFEMALE, "CmoonfemaleZ", OBSEG_ADDR(CmoonfemaleZ)},
    {MOONGUARD, "CmoonguardZ", OBSEG_ADDR(CmoonguardZ)},
    {NATALYA, "CnatalyaZ", OBSEG_ADDR(CnatalyaZ)},
    {NAVYGUARD, "CnavyguardZ", OBSEG_ADDR(CnavyguardZ)},
    {ODDJOB, "CoddjobZ", OBSEG_ADDR(CoddjobZ)},
    {OLIVEGUARD, "ColiveguardZ", OBSEG_ADDR(ColiveguardZ)},
    {ORUMOV, "CorumovZ", OBSEG_ADDR(CorumovZ)},
    {PILOT, "CpilotZ", OBSEG_ADDR(CpilotZ)},
    {REDMAN, "CredmanZ", OBSEG_ADDR(CredmanZ)},
    {RUSGUARD, "CrusguardZ", OBSEG_ADDR(CrusguardZ)},
    {SNOWBOND, "CsnowbondZ", OBSEG_ADDR(CsnowbondZ)},
    {SNOWGUARD, "CsnowguardZ", OBSEG_ADDR(CsnowguardZ)},
    {SPICEBOND, "CspicebondZ", OBSEG_ADDR(CspicebondZ)},
    {SUIT_LF_HAND, "Csuit_lf_handZ", OBSEG_ADDR(Csuit_lf_handZ)},
    {SUITBOND, "CsuitbondZ", OBSEG_ADDR(CsuitbondZ)},
    {TECHMAN, "CtechmanZ", OBSEG_ADDR(CtechmanZ)},
    {TECHWOMAN, "CtechwomanZ", OBSEG_ADDR(CtechwomanZ)},
    {TIMBERBOND, "CtimberbondZ", OBSEG_ADDR(CtimberbondZ)},
    {TREVELYAN, "CtrevelyanZ", OBSEG_ADDR(CtrevelyanZ)},
    {TREVGUARD, "CtrevguardZ", OBSEG_ADDR(CtrevguardZ)},
    {VALENTIN, "CvalentinZ", OBSEG_ADDR(CvalentinZ)},
    {XENIA, "CxeniaZ", OBSEG_ADDR(CxeniaZ)},

    {AK47, "Gak47Z", OBSEG_ADDR(Gak47Z)},
    {AUDIOTAPE, "GaudiotapeZ", OBSEG_ADDR(GaudiotapeZ)},
    {AUTOSHOT, "GautoshotZ", OBSEG_ADDR(GautoshotZ)},
    {BLACKBOX, "GblackboxZ", OBSEG_ADDR(GblackboxZ)},
    {BLUEPRINTS, "GblueprintsZ", OBSEG_ADDR(GblueprintsZ)},
    {BOMBCASE, "GbombcaseZ", OBSEG_ADDR(GbombcaseZ)},
    {BOMBDEFUSER, "GbombdefuserZ", OBSEG_ADDR(GbombdefuserZ)},
    {BRIEFCASE, "GbriefcaseZ", OBSEG_ADDR(GbriefcaseZ)},
    {BUG, "GbugZ", OBSEG_ADDR(GbugZ)},
    {BUGDETECTOR, "GbugdetectorZ", OBSEG_ADDR(GbugdetectorZ)},
    {BUNGEE, "GbungeeZ", OBSEG_ADDR(GbungeeZ)},
    {CAMERA, "GcameraZ", OBSEG_ADDR(GcameraZ)},
    {CARTBLUE, "GcartblueZ", OBSEG_ADDR(GcartblueZ)},
    {CARTRIDGE, "GcartridgeZ", OBSEG_ADDR(GcartridgeZ)},
    {CARTRIFLE, "GcartrifleZ", OBSEG_ADDR(GcartrifleZ)},
    {CARTSHELL, "GcartshellZ", OBSEG_ADDR(GcartshellZ)},
    {CIRCUITBOARD, "GcircuitboardZ", OBSEG_ADDR(GcircuitboardZ)},
    {CLIPBOARD, "GclipboardZ", OBSEG_ADDR(GclipboardZ)},
    {CREDITCARD, "GcreditcardZ", OBSEG_ADDR(GcreditcardZ)},
    {DARKGLASSES, "GdarkglassesZ", OBSEG_ADDR(GdarkglassesZ)},
    {DATATHIEF, "GdatathiefZ", OBSEG_ADDR(GdatathiefZ)},
    {DATTAPE, "GdattapeZ", OBSEG_ADDR(GdattapeZ)},
    {DOORDECODER, "GdoordecoderZ", OBSEG_ADDR(GdoordecoderZ)},
    {DOOREXPLODER, "GdoorexploderZ", OBSEG_ADDR(GdoorexploderZ)},
    {DOSSIERRED, "GdossierredZ", OBSEG_ADDR(GdossierredZ)},
    {DYNAMITE, "GdynamiteZ", OBSEG_ADDR(GdynamiteZ)},
    {EXPLOSIVEFLOPPY, "GexplosivefloppyZ", OBSEG_ADDR(GexplosivefloppyZ)},
    {EXPLOSIVEPEN, "GexplosivepenZ", OBSEG_ADDR(GexplosivepenZ)},
    {EXTINGUISHER, "GextinguisherZ", OBSEG_ADDR(GextinguisherZ)},
    {FINGERGUN, "GfingergunZ", OBSEG_ADDR(GfingergunZ)},
    {FIST, "GfistZ", OBSEG_ADDR(GfistZ)},
    {FLAREPISTOL, "GflarepistolZ", OBSEG_ADDR(GflarepistolZ)},
    {FNP90, "Gfnp90Z", OBSEG_ADDR(Gfnp90Z)},
    {GASKEYRING, "GgaskeyringZ", OBSEG_ADDR(GgaskeyringZ)},
    {GOLDBAR, "GgoldbarZ", OBSEG_ADDR(GgoldbarZ)},
    {GOLDENEYEKEY, "GgoldeneyekeyZ", OBSEG_ADDR(GgoldeneyekeyZ)},
    {GOLDENGUN, "GgoldengunZ", OBSEG_ADDR(GgoldengunZ)},
    {GOLDWPPK, "GgoldwppkZ", OBSEG_ADDR(GgoldwppkZ)},
    {GRENADE, "GgrenadeZ", OBSEG_ADDR(GgrenadeZ)},
    {GRENADELAUNCH, "GgrenadelaunchZ", OBSEG_ADDR(GgrenadelaunchZ)},
    {HEROIN, "GheroinZ", OBSEG_ADDR(GheroinZ)},
    {JOYPAD, "GjoypadZ", OBSEG_ADDR(GjoypadZ)},
    {KEYANALYSERCASE, "GkeyanalysercaseZ", OBSEG_ADDR(GkeyanalysercaseZ)},
    {KEYBOLT, "GkeyboltZ", OBSEG_ADDR(GkeyboltZ)},
    {KEYCARD, "GkeycardZ", OBSEG_ADDR(GkeycardZ)},
    {KEYYALE, "GkeyyaleZ", OBSEG_ADDR(GkeyyaleZ)},
    {KNIFE, "GknifeZ", OBSEG_ADDR(GknifeZ)},
    {LASER, "GlaserZ", OBSEG_ADDR(GlaserZ)},
    {LECTRE, "GlectreZ", OBSEG_ADDR(GlectreZ)},
    {LOCKEXPLODER, "GlockexploderZ", OBSEG_ADDR(GlockexploderZ)},
    {M16, "Gm16Z", OBSEG_ADDR(Gm16Z)},
    {MAP, "GmapZ", OBSEG_ADDR(GmapZ)},
    {MICROCAMERA, "GmicrocameraZ", OBSEG_ADDR(GmicrocameraZ)},
    {MICROCODE, "GmicrocodeZ", OBSEG_ADDR(GmicrocodeZ)},
    {MICROFILM, "GmicrofilmZ", OBSEG_ADDR(GmicrofilmZ)},
    {MONEY, "GmoneyZ", OBSEG_ADDR(GmoneyZ)},
    {MP5K, "Gmp5kZ", OBSEG_ADDR(Gmp5kZ)},
    {MP5KSIL, "Gmp5ksilZ", OBSEG_ADDR(Gmp5ksilZ)},
    {PITONGUN, "GpitongunZ", OBSEG_ADDR(GpitongunZ)},
    {PLANS, "GplansZ", OBSEG_ADDR(GplansZ)},
    {PLASTIQUE, "GplastiqueZ", OBSEG_ADDR(GplastiqueZ)},
    {POLARIZEDGLASSES, "GpolarizedglassesZ", OBSEG_ADDR(GpolarizedglassesZ)},
    {PROXIMITYMINE, "GproximitymineZ", OBSEG_ADDR(GproximitymineZ)},
    {REMOTEMINE, "GremotemineZ", OBSEG_ADDR(GremotemineZ)},
    {ROCKETLAUNCH, "GrocketlaunchZ", OBSEG_ADDR(GrocketlaunchZ)},
    {RUGER, "GrugerZ", OBSEG_ADDR(GrugerZ)},
    {SAFECRACKERCASE, "GsafecrackercaseZ", OBSEG_ADDR(GsafecrackercaseZ)},
    {SHOTGUN, "GshotgunZ", OBSEG_ADDR(GshotgunZ)},
    {SILVERWPPK, "GsilverwppkZ", OBSEG_ADDR(GsilverwppkZ)},
    {SKORPION, "GskorpionZ", OBSEG_ADDR(GskorpionZ)},
    {SNIPERRIFLE, "GsniperrifleZ", OBSEG_ADDR(GsniperrifleZ)},
    {SPECTRE, "GspectreZ", OBSEG_ADDR(GspectreZ)},
    {SPOOLTAPE, "GspooltapeZ", OBSEG_ADDR(GspooltapeZ)},
    {SPYFILE, "GspyfileZ", OBSEG_ADDR(GspyfileZ)},
    {STAFFLIST, "GstafflistZ", OBSEG_ADDR(GstafflistZ)},
    {TASER, "GtaserZ", OBSEG_ADDR(GtaserZ)},
    {THROWKNIFE, "GthrowknifeZ", OBSEG_ADDR(GthrowknifeZ)},
    {TIMEDMINE, "GtimedmineZ", OBSEG_ADDR(GtimedmineZ)},
    {TRIGGER, "GtriggerZ", OBSEG_ADDR(GtriggerZ)},
    {TT33, "Gtt33Z", OBSEG_ADDR(Gtt33Z)},
    {UZI, "GuziZ", OBSEG_ADDR(GuziZ)},
    {VIDEOTAPE, "GvideotapeZ", OBSEG_ADDR(GvideotapeZ)},
    {WATCHCOMMUNICATOR, "GwatchcommunicatorZ", OBSEG_ADDR(GwatchcommunicatorZ)},
    {WATCHGEIGERCOUNTER, "GwatchgeigercounterZ", OBSEG_ADDR(GwatchgeigercounterZ)},
    {WATCHIDENTIFIER, "GwatchidentifierZ", OBSEG_ADDR(GwatchidentifierZ)},
    {WATCHLASER, "GwatchlaserZ", OBSEG_ADDR(GwatchlaserZ)},
    {WATCHMAGNETATTRACT, "GwatchmagnetattractZ", OBSEG_ADDR(GwatchmagnetattractZ)},
    {WATCHMAGNETREPEL, "GwatchmagnetrepelZ", OBSEG_ADDR(GwatchmagnetrepelZ)},
    {WEAPONCASE, "GweaponcaseZ", OBSEG_ADDR(GweaponcaseZ)},
    {WPPK, "GwppkZ", OBSEG_ADDR(GwppkZ)},
    {WPPKSIL, "GwppksilZ", OBSEG_ADDR(GwppksilZ)},
    {WRISTDART, "GwristdartZ", OBSEG_ADDR(GwristdartZ)},

    {ICBM, "PICBMZ", OBSEG_ADDR(PICBMZ)},
    {ICBM_NOSE, "PICBM_noseZ", OBSEG_ADDR(PICBM_noseZ)},
    {AK47MAG, "Pak47magZ", OBSEG_ADDR(Pak47magZ)},
    {ALARM1, "Palarm1Z", OBSEG_ADDR(Palarm1Z)},
    {ALARM2, "Palarm2Z", OBSEG_ADDR(Palarm2Z)},
    {AMMO_CRATE1, "Pammo_crate1Z", OBSEG_ADDR(Pammo_crate1Z)},
    {AMMO_CRATE2, "Pammo_crate2Z", OBSEG_ADDR(Pammo_crate2Z)},
    {AMMO_CRATE3, "Pammo_crate3Z", OBSEG_ADDR(Pammo_crate3Z)},
    {AMMO_CRATE4, "Pammo_crate4Z", OBSEG_ADDR(Pammo_crate4Z)},
    {AMMO_CRATE5, "Pammo_crate5Z", OBSEG_ADDR(Pammo_crate5Z)},
    {APC, "PapcZ", OBSEG_ADDR(PapcZ)},
    {ARCHSECDOOR1, "Parchsecdoor1Z", OBSEG_ADDR(Parchsecdoor1Z)},
    {ARCHSECDOOR2, "Parchsecdoor2Z", OBSEG_ADDR(Parchsecdoor2Z)},
    {ARTIC, "ParticZ", OBSEG_ADDR(ParticZ)},
    {ARTICTRAILER, "PartictrailerZ", OBSEG_ADDR(PartictrailerZ)},
    {BARRICADE, "PbarricadeZ", OBSEG_ADDR(PbarricadeZ)},
    {BIN1, "Pbin1Z", OBSEG_ADDR(Pbin1Z)},
    {BLOTTER1, "Pblotter1Z", OBSEG_ADDR(Pblotter1Z)},
    {BODYARMOUR, "PbodyarmourZ", OBSEG_ADDR(PbodyarmourZ)},
    {BODYARMOURVEST, "PbodyarmourvestZ", OBSEG_ADDR(PbodyarmourvestZ)},
    {BOLLARD, "PbollardZ", OBSEG_ADDR(PbollardZ)},
    {BOMB, "PbombZ", OBSEG_ADDR(PbombZ)},
    {BOOK1, "Pbook1Z", OBSEG_ADDR(Pbook1Z)},
    {BOOKSHELF1, "Pbookshelf1Z", OBSEG_ADDR(Pbookshelf1Z)},
    {BORG_CRATE, "Pborg_crateZ", OBSEG_ADDR(Pborg_crateZ)},
    {BOXCARTRIDGES, "PboxcartridgesZ", OBSEG_ADDR(PboxcartridgesZ)},
    {BOXES2X4, "Pboxes2x4Z", OBSEG_ADDR(Pboxes2x4Z)},
    {BOXES3X4, "Pboxes3x4Z", OBSEG_ADDR(Pboxes3x4Z)},
    {BOXES4X4, "Pboxes4x4Z", OBSEG_ADDR(Pboxes4x4Z)},
    {BRAKEUNIT, "PbrakeunitZ", OBSEG_ADDR(PbrakeunitZ)},
    {BRIDGE_CONSOLE1A, "Pbridge_console1aZ", OBSEG_ADDR(Pbridge_console1aZ)},
    {BRIDGE_CONSOLE1B, "Pbridge_console1bZ", OBSEG_ADDR(Pbridge_console1bZ)},
    {BRIDGE_CONSOLE2A, "Pbridge_console2aZ", OBSEG_ADDR(Pbridge_console2aZ)},
    {BRIDGE_CONSOLE2B, "Pbridge_console2bZ", OBSEG_ADDR(Pbridge_console2bZ)},
    {BRIDGE_CONSOLE3A, "Pbridge_console3aZ", OBSEG_ADDR(Pbridge_console3aZ)},
    {BRIDGE_CONSOLE3B, "Pbridge_console3bZ", OBSEG_ADDR(Pbridge_console3bZ)},
    {CARBMW, "PcarbmwZ", OBSEG_ADDR(PcarbmwZ)},
    {CARD_BOX1, "Pcard_box1Z", OBSEG_ADDR(Pcard_box1Z)},
    {CARD_BOX2, "Pcard_box2Z", OBSEG_ADDR(Pcard_box2Z)},
    {CARD_BOX3, "Pcard_box3Z", OBSEG_ADDR(Pcard_box3Z)},
    {CARD_BOX4_LG, "Pcard_box4_lgZ", OBSEG_ADDR(Pcard_box4_lgZ)},
    {CARD_BOX5_LG, "Pcard_box5_lgZ", OBSEG_ADDR(Pcard_box5_lgZ)},
    {CARD_BOX6_LG, "Pcard_box6_lgZ", OBSEG_ADDR(Pcard_box6_lgZ)},
    {CARESCORT, "PcarescortZ", OBSEG_ADDR(PcarescortZ)},
    {CARGOLF, "PcargolfZ", OBSEG_ADDR(PcargolfZ)},
    {CARWEIRD, "PcarweirdZ", OBSEG_ADDR(PcarweirdZ)},
    {CARZIL, "PcarzilZ", OBSEG_ADDR(PcarzilZ)},
    {CCTV, "PcctvZ", OBSEG_ADDR(PcctvZ)},
    {CHRAUDIOTAPE, "PchraudiotapeZ", OBSEG_ADDR(PchraudiotapeZ)},
    {CHRAUTOSHOT, "PchrautoshotZ", OBSEG_ADDR(PchrautoshotZ)},
    {CHRBLACKBOX, "PchrblackboxZ", OBSEG_ADDR(PchrblackboxZ)},
    {CHRBLUEPRINTS, "PchrblueprintsZ", OBSEG_ADDR(PchrblueprintsZ)},
    {CHRBOMBCASE, "PchrbombcaseZ", OBSEG_ADDR(PchrbombcaseZ)},
    {CHRBOMBDEFUSER, "PchrbombdefuserZ", OBSEG_ADDR(PchrbombdefuserZ)},
    {CHRBRIEFCASE, "PchrbriefcaseZ", OBSEG_ADDR(PchrbriefcaseZ)},
    {CHRBUG, "PchrbugZ", OBSEG_ADDR(PchrbugZ)},
    {CHRBUGDETECTOR, "PchrbugdetectorZ", OBSEG_ADDR(PchrbugdetectorZ)},
    {CHRBUNGEE, "PchrbungeeZ", OBSEG_ADDR(PchrbungeeZ)},
    {CHRCAMERA, "PchrcameraZ", OBSEG_ADDR(PchrcameraZ)},
    {CHRCIRCUITBOARD, "PchrcircuitboardZ", OBSEG_ADDR(PchrcircuitboardZ)},
    {CHRCLIPBOARD, "PchrclipboardZ", OBSEG_ADDR(PchrclipboardZ)},
    {CHRCREDITCARD, "PchrcreditcardZ", OBSEG_ADDR(PchrcreditcardZ)},
    {CHRDARKGLASSES, "PchrdarkglassesZ", OBSEG_ADDR(PchrdarkglassesZ)},
    {CHRDATATHIEF, "PchrdatathiefZ", OBSEG_ADDR(PchrdatathiefZ)},
    {CHRDATTAPE, "PchrdattapeZ", OBSEG_ADDR(PchrdattapeZ)},
    {CHRDOORDECODER, "PchrdoordecoderZ", OBSEG_ADDR(PchrdoordecoderZ)},
    {CHRDOOREXPLODER, "PchrdoorexploderZ", OBSEG_ADDR(PchrdoorexploderZ)},
    {CHRDOSSIERRED, "PchrdossierredZ", OBSEG_ADDR(PchrdossierredZ)},
    {CHRDYNAMITE, "PchrdynamiteZ", OBSEG_ADDR(PchrdynamiteZ)},
    {CHREXPLOSIVEPEN, "PchrexplosivepenZ", OBSEG_ADDR(PchrexplosivepenZ)},
    {CHREXTINGUISHER, "PchrextinguisherZ", OBSEG_ADDR(PchrextinguisherZ)},
    {CHRFINGERGUN, "PchrfingergunZ", OBSEG_ADDR(PchrfingergunZ)},
    {CHRFLAREPISTOL, "PchrflarepistolZ", OBSEG_ADDR(PchrflarepistolZ)},
    {CHRFNP90, "Pchrfnp90Z", OBSEG_ADDR(Pchrfnp90Z)},
    {CHRGASKEYRING, "PchrgaskeyringZ", OBSEG_ADDR(PchrgaskeyringZ)},
    {CHRGOLDBAR, "PchrgoldbarZ", OBSEG_ADDR(PchrgoldbarZ)},
    {CHRGOLDEN, "PchrgoldenZ", OBSEG_ADDR(PchrgoldenZ)},
    {CHRGOLDENEYEKEY, "PchrgoldeneyekeyZ", OBSEG_ADDR(PchrgoldeneyekeyZ)},
    {CHRGOLDWPPK, "PchrgoldwppkZ", OBSEG_ADDR(PchrgoldwppkZ)},
    {CHRGRENADE, "PchrgrenadeZ", OBSEG_ADDR(PchrgrenadeZ)},
    {CHRGRENADELAUNCH, "PchrgrenadelaunchZ", OBSEG_ADDR(PchrgrenadelaunchZ)},
    {CHRGRENADEROUND, "PchrgrenaderoundZ", OBSEG_ADDR(PchrgrenaderoundZ)},
    {CHRHEROIN, "PchrheroinZ", OBSEG_ADDR(PchrheroinZ)},
    {CHRKALASH, "PchrkalashZ", OBSEG_ADDR(PchrkalashZ)},
    {CHRKEYANALYSERCASE, "PchrkeyanalysercaseZ", OBSEG_ADDR(PchrkeyanalysercaseZ)},
    {CHRKEYBOLT, "PchrkeyboltZ", OBSEG_ADDR(PchrkeyboltZ)},
    {CHRKEYYALE, "PchrkeyyaleZ", OBSEG_ADDR(PchrkeyyaleZ)},
    {CHRKNIFE, "PchrknifeZ", OBSEG_ADDR(PchrknifeZ)},
    {CHRLASER, "PchrlaserZ", OBSEG_ADDR(PchrlaserZ)},
    {CHRLECTRE, "PchrlectreZ", OBSEG_ADDR(PchrlectreZ)},
    {CHRLOCKEXPLODER, "PchrlockexploderZ", OBSEG_ADDR(PchrlockexploderZ)},
    {CHRM16, "Pchrm16Z", OBSEG_ADDR(Pchrm16Z)},
    {CHRMAP, "PchrmapZ", OBSEG_ADDR(PchrmapZ)},
    {CHRMICROCAMERA, "PchrmicrocameraZ", OBSEG_ADDR(PchrmicrocameraZ)},
    {CHRMICROCODE, "PchrmicrocodeZ", OBSEG_ADDR(PchrmicrocodeZ)},
    {CHRMICROFILM, "PchrmicrofilmZ", OBSEG_ADDR(PchrmicrofilmZ)},
    {CHRMONEY, "PchrmoneyZ", OBSEG_ADDR(PchrmoneyZ)},
    {CHRMP5K, "Pchrmp5kZ", OBSEG_ADDR(Pchrmp5kZ)},
    {CHRMP5KSIL, "Pchrmp5ksilZ", OBSEG_ADDR(Pchrmp5ksilZ)},
    {CHRPITONGUN, "PchrpitongunZ", OBSEG_ADDR(PchrpitongunZ)},
    {CHRPLANS, "PchrplansZ", OBSEG_ADDR(PchrplansZ)},
    {CHRPLASTIQUE, "PchrplastiqueZ", OBSEG_ADDR(PchrplastiqueZ)},
    {CHRPOLARIZEDGLASSES, "PchrpolarizedglassesZ", OBSEG_ADDR(PchrpolarizedglassesZ)},
    {CHRPROXIMITYMINE, "PchrproximitymineZ", OBSEG_ADDR(PchrproximitymineZ)},
    {CHRREMOTEMINE, "PchrremotemineZ", OBSEG_ADDR(PchrremotemineZ)},
    {CHRROCKET, "PchrrocketZ", OBSEG_ADDR(PchrrocketZ)},
    {CHRROCKETLAUNCH, "PchrrocketlaunchZ", OBSEG_ADDR(PchrrocketlaunchZ)},
    {CHRRUGER, "PchrrugerZ", OBSEG_ADDR(PchrrugerZ)},
    {CHRSAFECRACKERCASE, "PchrsafecrackercaseZ", OBSEG_ADDR(PchrsafecrackercaseZ)},
    {CHRSHOTGUN, "PchrshotgunZ", OBSEG_ADDR(PchrshotgunZ)},
    {CHRSILVERWPPK, "PchrsilverwppkZ", OBSEG_ADDR(PchrsilverwppkZ)},
    {CHRSKORPION, "PchrskorpionZ", OBSEG_ADDR(PchrskorpionZ)},
    {CHRSNIPERRIFLE, "PchrsniperrifleZ", OBSEG_ADDR(PchrsniperrifleZ)},
    {CHRSPECTRE, "PchrspectreZ", OBSEG_ADDR(PchrspectreZ)},
    {CHRSPOOLTAPE, "PchrspooltapeZ", OBSEG_ADDR(PchrspooltapeZ)},
    {CHRSPYFILE, "PchrspyfileZ", OBSEG_ADDR(PchrspyfileZ)},
    {CHRSTAFFLIST, "PchrstafflistZ", OBSEG_ADDR(PchrstafflistZ)},
    {CHRTESTTUBE, "PchrtesttubeZ", OBSEG_ADDR(PchrtesttubeZ)},
    {CHRTHROWKNIFE, "PchrthrowknifeZ", OBSEG_ADDR(PchrthrowknifeZ)},
    {CHRTIMEDMINE, "PchrtimedmineZ", OBSEG_ADDR(PchrtimedmineZ)},
    {CHRTT33, "Pchrtt33Z", OBSEG_ADDR(Pchrtt33Z)},
    {CHRUZI, "PchruziZ", OBSEG_ADDR(PchruziZ)},
    {CHRVIDEOTAPE, "PchrvideotapeZ", OBSEG_ADDR(PchrvideotapeZ)},
    {CHRWEAPONCASE, "PchrweaponcaseZ", OBSEG_ADDR(PchrweaponcaseZ)},
    {CHRWPPK, "PchrwppkZ", OBSEG_ADDR(PchrwppkZ)},
    {CHRWPPKSIL, "PchrwppksilZ", OBSEG_ADDR(PchrwppksilZ)},
    {CHRWRISTDART, "PchrwristdartZ", OBSEG_ADDR(PchrwristdartZ)},
    {CONSOLE1, "Pconsole1Z", OBSEG_ADDR(Pconsole1Z)},
    {CONSOLE2, "Pconsole2Z", OBSEG_ADDR(Pconsole2Z)},
    {CONSOLE3, "Pconsole3Z", OBSEG_ADDR(Pconsole3Z)},
    {CONSOLE_SEV2A, "Pconsole_sev2aZ", OBSEG_ADDR(Pconsole_sev2aZ)},
    {CONSOLE_SEV2B, "Pconsole_sev2bZ", OBSEG_ADDR(Pconsole_sev2bZ)},
    {CONSOLE_SEV2C, "Pconsole_sev2cZ", OBSEG_ADDR(Pconsole_sev2cZ)},
    {CONSOLE_SEV2D, "Pconsole_sev2dZ", OBSEG_ADDR(Pconsole_sev2dZ)},
    {CONSOLE_SEV_GEA, "Pconsole_sev_GEaZ", OBSEG_ADDR(Pconsole_sev_GEaZ)},
    {CONSOLE_SEV_GEB, "Pconsole_sev_GEbZ", OBSEG_ADDR(Pconsole_sev_GEbZ)},
    {CONSOLE_SEVA, "Pconsole_sevaZ", OBSEG_ADDR(Pconsole_sevaZ)},
    {CONSOLE_SEVB, "Pconsole_sevbZ", OBSEG_ADDR(Pconsole_sevbZ)},
    {CONSOLE_SEVC, "Pconsole_sevcZ", OBSEG_ADDR(Pconsole_sevcZ)},
    {CONSOLE_SEVD, "Pconsole_sevdZ", OBSEG_ADDR(Pconsole_sevdZ)},
    {CRYPTDOOR1A, "Pcryptdoor1aZ", OBSEG_ADDR(Pcryptdoor1aZ)},
    {CRYPTDOOR1B, "Pcryptdoor1bZ", OBSEG_ADDR(Pcryptdoor1bZ)},
    {CRYPTDOOR2A, "Pcryptdoor2aZ", OBSEG_ADDR(Pcryptdoor2aZ)},
    {CRYPTDOOR2B, "Pcryptdoor2bZ", OBSEG_ADDR(Pcryptdoor2bZ)},
    {CRYPTDOOR3, "Pcryptdoor3Z", OBSEG_ADDR(Pcryptdoor3Z)},
    {CRYPTDOOR4, "Pcryptdoor4Z", OBSEG_ADDR(Pcryptdoor4Z)},
    {DAMCHAINDOOR, "PdamchaindoorZ", OBSEG_ADDR(PdamchaindoorZ)},
    {DAMGATEDOOR, "PdamgatedoorZ", OBSEG_ADDR(PdamgatedoorZ)},
    {DAMTUNDOOR, "PdamtundoorZ", OBSEG_ADDR(PdamtundoorZ)},
    {DEPOT_DOOR_STEEL, "Pdepot_door_steelZ", OBSEG_ADDR(Pdepot_door_steelZ)},
    {DEPOT_GATE_ENTRY, "Pdepot_gate_entryZ", OBSEG_ADDR(Pdepot_gate_entryZ)},
    {DESK1, "Pdesk1Z", OBSEG_ADDR(Pdesk1Z)},
    {DESK2, "Pdesk2Z", OBSEG_ADDR(Pdesk2Z)},
    {DESK_ARECIBO1, "Pdesk_arecibo1Z", OBSEG_ADDR(Pdesk_arecibo1Z)},
    {DESK_LAMP2, "Pdesk_lamp2Z", OBSEG_ADDR(Pdesk_lamp2Z)},
    {DEST_ENGINE, "Pdest_engineZ", OBSEG_ADDR(Pdest_engineZ)},
    {DEST_EXOCET, "Pdest_exocetZ", OBSEG_ADDR(Pdest_exocetZ)},
    {DEST_GUN, "Pdest_gunZ", OBSEG_ADDR(Pdest_gunZ)},
    {DEST_HARPOON, "Pdest_harpoonZ", OBSEG_ADDR(Pdest_harpoonZ)},
    {DEST_SEAWOLF, "Pdest_seawolfZ", OBSEG_ADDR(Pdest_seawolfZ)},
    {DISC_READER, "Pdisc_readerZ", OBSEG_ADDR(Pdisc_readerZ)},
    {DISK_DRIVE1, "Pdisk_drive1Z", OBSEG_ADDR(Pdisk_drive1Z)},
    {DOOR_AZT_CHAIR, "Pdoor_azt_chairZ", OBSEG_ADDR(Pdoor_azt_chairZ)},
    {DOOR_AZT_DESK, "Pdoor_azt_deskZ", OBSEG_ADDR(Pdoor_azt_deskZ)},
    {DOOR_AZT_DESK_TOP, "Pdoor_azt_desk_topZ", OBSEG_ADDR(Pdoor_azt_desk_topZ)},
    {DOOR_AZTEC, "Pdoor_aztecZ", OBSEG_ADDR(Pdoor_aztecZ)},
    {DOOR_DEST1, "Pdoor_dest1Z", OBSEG_ADDR(Pdoor_dest1Z)},
    {DOOR_DEST2, "Pdoor_dest2Z", OBSEG_ADDR(Pdoor_dest2Z)},
    {DOOR_EYELID, "Pdoor_eyelidZ", OBSEG_ADDR(Pdoor_eyelidZ)},
    {DOOR_IRIS, "Pdoor_irisZ", OBSEG_ADDR(Pdoor_irisZ)},
    {DOOR_MF, "Pdoor_mfZ", OBSEG_ADDR(Pdoor_mfZ)},
    {DOOR_ROLLER1, "Pdoor_roller1Z", OBSEG_ADDR(Pdoor_roller1Z)},
    {DOOR_ROLLER2, "Pdoor_roller2Z", OBSEG_ADDR(Pdoor_roller2Z)},
    {DOOR_ROLLER3, "Pdoor_roller3Z", OBSEG_ADDR(Pdoor_roller3Z)},
    {DOOR_ROLLER4, "Pdoor_roller4Z", OBSEG_ADDR(Pdoor_roller4Z)},
    {DOOR_ROLLERTRAIN, "Pdoor_rollertrainZ", OBSEG_ADDR(Pdoor_rollertrainZ)},
    {DOOR_ST_AREC1, "Pdoor_st_arec1Z", OBSEG_ADDR(Pdoor_st_arec1Z)},
    {DOOR_ST_AREC2, "Pdoor_st_arec2Z", OBSEG_ADDR(Pdoor_st_arec2Z)},
    {DOOR_WIN, "Pdoor_winZ", OBSEG_ADDR(Pdoor_winZ)},
    {DOORCONSOLE, "PdoorconsoleZ", OBSEG_ADDR(PdoorconsoleZ)},
    {DOORPANEL, "PdoorpanelZ", OBSEG_ADDR(PdoorpanelZ)},
    {DOORPRISON1, "Pdoorprison1Z", OBSEG_ADDR(Pdoorprison1Z)},
    {DOORSTATGATE, "PdoorstatgateZ", OBSEG_ADDR(PdoorstatgateZ)},
    {EXPLOSIONBIT, "PexplosionbitZ", OBSEG_ADDR(PexplosionbitZ)},
    {FILING_CABINET1, "Pfiling_cabinet1Z", OBSEG_ADDR(Pfiling_cabinet1Z)},
    {FLAG, "PflagZ", OBSEG_ADDR(PflagZ)},
    {FLOPPY, "PfloppyZ", OBSEG_ADDR(PfloppyZ)},
    {FNP90MAG, "Pfnp90magZ", OBSEG_ADDR(Pfnp90magZ)},
    {GAS_PLANT_MET1_DO1, "Pgas_plant_met1_do1Z", OBSEG_ADDR(Pgas_plant_met1_do1Z)},
    {GAS_PLANT_SW2_DO1, "Pgas_plant_sw2_do1Z", OBSEG_ADDR(Pgas_plant_sw2_do1Z)},
    {GAS_PLANT_SW3_DO1, "Pgas_plant_sw3_do1Z", OBSEG_ADDR(Pgas_plant_sw3_do1Z)},
    {GAS_PLANT_SW4_DO1, "Pgas_plant_sw4_do1Z", OBSEG_ADDR(Pgas_plant_sw4_do1Z)},
    {GAS_PLANT_SW_DO1, "Pgas_plant_sw_do1Z", OBSEG_ADDR(Pgas_plant_sw_do1Z)},
    {GAS_PLANT_WC_CUB1, "Pgas_plant_wc_cub1Z", OBSEG_ADDR(Pgas_plant_wc_cub1Z)},
    {GASBARREL, "PgasbarrelZ", OBSEG_ADDR(PgasbarrelZ)},
    {GASBARRELS, "PgasbarrelsZ", OBSEG_ADDR(PgasbarrelsZ)},
    {GASPLANT_CLEAR_DOOR, "Pgasplant_clear_doorZ", OBSEG_ADDR(Pgasplant_clear_doorZ)},
    {GASTANK, "PgastankZ", OBSEG_ADDR(PgastankZ)},
    {GLASSWARE1, "Pglassware1Z", OBSEG_ADDR(Pglassware1Z)},
    {GLASSWARE2, "Pglassware2Z", OBSEG_ADDR(Pglassware2Z)},
    {GLASSWARE3, "Pglassware3Z", OBSEG_ADDR(Pglassware3Z)},
    {GLASSWARE4, "Pglassware4Z", OBSEG_ADDR(Pglassware4Z)},
    {GOLDENEYELOGO, "PgoldeneyelogoZ", OBSEG_ADDR(PgoldeneyelogoZ)},
    {GOLDENSHELLS, "PgoldenshellsZ", OBSEG_ADDR(PgoldenshellsZ)},
    {GROUNDGUN, "PgroundgunZ", OBSEG_ADDR(PgroundgunZ)},
    {GUN_RUNWAY1, "Pgun_runway1Z", OBSEG_ADDR(Pgun_runway1Z)},
    {HATBERET, "PhatberetZ", OBSEG_ADDR(PhatberetZ)},
    {HATBERETBLUE, "PhatberetblueZ", OBSEG_ADDR(PhatberetblueZ)},
    {HATBERETRED, "PhatberetredZ", OBSEG_ADDR(PhatberetredZ)},
    {HATCHBOLT, "PhatchboltZ", OBSEG_ADDR(PhatchboltZ)},
    {HATCHDOOR, "PhatchdoorZ", OBSEG_ADDR(PhatchdoorZ)},
    {HATCHSEVX, "PhatchsevxZ", OBSEG_ADDR(PhatchsevxZ)},
    {HATFURRY, "PhatfurryZ", OBSEG_ADDR(PhatfurryZ)},
    {HATFURRYBLACK, "PhatfurryblackZ", OBSEG_ADDR(PhatfurryblackZ)},
    {HATFURRYBROWN, "PhatfurrybrownZ", OBSEG_ADDR(PhatfurrybrownZ)},
    {HATHELMET, "PhathelmetZ", OBSEG_ADDR(PhathelmetZ)},
    {HATHELMETGREY, "PhathelmetgreyZ", OBSEG_ADDR(PhathelmetgreyZ)},
    {HATMOON, "PhatmoonZ", OBSEG_ADDR(PhatmoonZ)},
    {HATPEAKED, "PhatpeakedZ", OBSEG_ADDR(PhatpeakedZ)},
    {HATTBIRD, "PhattbirdZ", OBSEG_ADDR(PhattbirdZ)},
    {HATTBIRDBROWN, "PhattbirdbrownZ", OBSEG_ADDR(PhattbirdbrownZ)},
    {HELICOPTER, "PhelicopterZ", OBSEG_ADDR(PhelicopterZ)},
    {HIND, "PhindZ", OBSEG_ADDR(PhindZ)},
    {JEEP, "PjeepZ", OBSEG_ADDR(PjeepZ)},
    {JERRY_CAN1, "Pjerry_can1Z", OBSEG_ADDR(Pjerry_can1Z)},
    {JUNGLE3_TREE, "Pjungle3_treeZ", OBSEG_ADDR(Pjungle3_treeZ)},
    {JUNGLE5_TREE, "Pjungle5_treeZ", OBSEG_ADDR(Pjungle5_treeZ)},
    {KEY_HOLDER, "Pkey_holderZ", OBSEG_ADDR(Pkey_holderZ)},
    {KEYBOARD1, "Pkeyboard1Z", OBSEG_ADDR(Pkeyboard1Z)},
    {KIT_UNITS1, "Pkit_units1Z", OBSEG_ADDR(Pkit_units1Z)},
    {LABBENCH, "PlabbenchZ", OBSEG_ADDR(PlabbenchZ)},
    {LANDMINE, "PlandmineZ", OBSEG_ADDR(PlandmineZ)},
    {LEGALPAGE, "PlegalpageZ", OBSEG_ADDR(PlegalpageZ)},
    {LETTER_TRAY1, "Pletter_tray1Z", OBSEG_ADDR(Pletter_tray1Z)},
    {LOCKER3, "Plocker3Z", OBSEG_ADDR(Plocker3Z)},
    {LOCKER4, "Plocker4Z", OBSEG_ADDR(Plocker4Z)},
    {M16MAG, "Pm16magZ", OBSEG_ADDR(Pm16magZ)},
    {MAGNUMSHELLS, "PmagnumshellsZ", OBSEG_ADDR(PmagnumshellsZ)},
    {MAINFRAME1, "Pmainframe1Z", OBSEG_ADDR(Pmainframe1Z)},
    {MAINFRAME2, "Pmainframe2Z", OBSEG_ADDR(Pmainframe2Z)},
    {METAL_CHAIR1, "Pmetal_chair1Z", OBSEG_ADDR(Pmetal_chair1Z)},
    {METAL_CRATE1, "Pmetal_crate1Z", OBSEG_ADDR(Pmetal_crate1Z)},
    {METAL_CRATE2, "Pmetal_crate2Z", OBSEG_ADDR(Pmetal_crate2Z)},
    {METAL_CRATE3, "Pmetal_crate3Z", OBSEG_ADDR(Pmetal_crate3Z)},
    {METAL_CRATE4, "Pmetal_crate4Z", OBSEG_ADDR(Pmetal_crate4Z)},
    {MILCOPTER, "PmilcopterZ", OBSEG_ADDR(PmilcopterZ)},
    {MILTRUCK, "PmiltruckZ", OBSEG_ADDR(PmiltruckZ)},
    {MISSILE_RACK2, "Pmissile_rack2Z", OBSEG_ADDR(Pmissile_rack2Z)},
    {MISSILE_RACK, "Pmissile_rackZ", OBSEG_ADDR(Pmissile_rackZ)},
    {MODEMBOX, "PmodemboxZ", OBSEG_ADDR(PmodemboxZ)},
    {MOTORBIKE, "PmotorbikeZ", OBSEG_ADDR(PmotorbikeZ)},
    {MP5KMAG, "Pmp5kmagZ", OBSEG_ADDR(Pmp5kmagZ)},
    {NINTENDOLOGO, "PnintendologoZ", OBSEG_ADDR(PnintendologoZ)},
    {OIL_DRUM1, "Poil_drum1Z", OBSEG_ADDR(Poil_drum1Z)},
    {OIL_DRUM2, "Poil_drum2Z", OBSEG_ADDR(Poil_drum2Z)},
    {OIL_DRUM3, "Poil_drum3Z", OBSEG_ADDR(Poil_drum3Z)},
    {OIL_DRUM5, "Poil_drum5Z", OBSEG_ADDR(Poil_drum5Z)},
    {OIL_DRUM6, "Poil_drum6Z", OBSEG_ADDR(Poil_drum6Z)},
    {OIL_DRUM7, "Poil_drum7Z", OBSEG_ADDR(Poil_drum7Z)},
    {PADLOCK, "PpadlockZ", OBSEG_ADDR(PpadlockZ)},
    {PALM, "PpalmZ", OBSEG_ADDR(PpalmZ)},
    {PALMTREE, "PpalmtreeZ", OBSEG_ADDR(PpalmtreeZ)},
    {PHONE1, "Pphone1Z", OBSEG_ADDR(Pphone1Z)},
    {PLANE, "PplaneZ", OBSEG_ADDR(PplaneZ)},
    {PLANT11, "Pplant11Z", OBSEG_ADDR(Pplant11Z)},
    {PLANT1, "Pplant1Z", OBSEG_ADDR(Pplant1Z)},
    {PLANT2, "Pplant2Z", OBSEG_ADDR(Pplant2Z)},
    {PLANT2B, "Pplant2bZ", OBSEG_ADDR(Pplant2bZ)},
    {PLANT3, "Pplant3Z", OBSEG_ADDR(Pplant3Z)},
    {RADIO_UNIT1, "Pradio_unit1Z", OBSEG_ADDR(Pradio_unit1Z)},
    {RADIO_UNIT2, "Pradio_unit2Z", OBSEG_ADDR(Pradio_unit2Z)},
    {RADIO_UNIT3, "Pradio_unit3Z", OBSEG_ADDR(Pradio_unit3Z)},
    {RADIO_UNIT4, "Pradio_unit4Z", OBSEG_ADDR(Pradio_unit4Z)},
    {ROOFGUN, "ProofgunZ", OBSEG_ADDR(ProofgunZ)},
    {SAFE, "PsafeZ", OBSEG_ADDR(PsafeZ)},
    {SAFEDOOR, "PsafedoorZ", OBSEG_ADDR(PsafedoorZ)},
    {SAT1_REFLECT, "Psat1_reflectZ", OBSEG_ADDR(Psat1_reflectZ)},
    {SATBOX, "PsatboxZ", OBSEG_ADDR(PsatboxZ)},
    {SATDISH, "PsatdishZ", OBSEG_ADDR(PsatdishZ)},
    {SEC_PANEL, "Psec_panelZ", OBSEG_ADDR(Psec_panelZ)},
    {SEV_DOOR3, "Psev_door3Z", OBSEG_ADDR(Psev_door3Z)},
    {SEV_DOOR3_WIND, "Psev_door3_windZ", OBSEG_ADDR(Psev_door3_windZ)},
    {SEV_DOOR4_WIND, "Psev_door4_windZ", OBSEG_ADDR(Psev_door4_windZ)},
    {SEV_DOOR, "Psev_doorZ", OBSEG_ADDR(Psev_doorZ)},
    {SEV_DOOR_V1, "Psev_door_v1Z", OBSEG_ADDR(Psev_door_v1Z)},
    {SEV_TRISLIDE, "Psev_trislideZ", OBSEG_ADDR(Psev_trislideZ)},
    {SEVDISH, "PsevdishZ", OBSEG_ADDR(PsevdishZ)},
    {SEVDOORMETSLIDE, "PsevdoormetslideZ", OBSEG_ADDR(PsevdoormetslideZ)},
    {SEVDOORNOWIND, "PsevdoornowindZ", OBSEG_ADDR(PsevdoornowindZ)},
    {SEVDOORWIND, "PsevdoorwindZ", OBSEG_ADDR(PsevdoorwindZ)},
    {SEVDOORWOOD, "PsevdoorwoodZ", OBSEG_ADDR(PsevdoorwoodZ)},
    {SHUTTLE, "PshuttleZ", OBSEG_ADDR(PshuttleZ)},
    {SHUTTLE_DOOR_L, "Pshuttle_door_lZ", OBSEG_ADDR(Pshuttle_door_lZ)},
    {SHUTTLE_DOOR_R, "Pshuttle_door_rZ", OBSEG_ADDR(Pshuttle_door_rZ)},
    {SILENCER, "PsilencerZ", OBSEG_ADDR(PsilencerZ)},
    {SILO_LIFT_DOOR, "Psilo_lift_doorZ", OBSEG_ADDR(Psilo_lift_doorZ)},
    {SILOTOPDOOR, "PsilotopdoorZ", OBSEG_ADDR(PsilotopdoorZ)},
    {SKORPIONMAG, "PskorpionmagZ", OBSEG_ADDR(PskorpionmagZ)},
    {SPECTREMAG, "PspectremagZ", OBSEG_ADDR(PspectremagZ)},
    {SPEEDBOAT, "PspeedboatZ", OBSEG_ADDR(PspeedboatZ)},
    {ST_PETE_ROOM_1I, "Pst_pete_room_1iZ", OBSEG_ADDR(Pst_pete_room_1iZ)},
    {ST_PETE_ROOM_2I, "Pst_pete_room_2iZ", OBSEG_ADDR(Pst_pete_room_2iZ)},
    {ST_PETE_ROOM_3T, "Pst_pete_room_3tZ", OBSEG_ADDR(Pst_pete_room_3tZ)},
    {ST_PETE_ROOM_5C, "Pst_pete_room_5cZ", OBSEG_ADDR(Pst_pete_room_5cZ)},
    {ST_PETE_ROOM_6C, "Pst_pete_room_6cZ", OBSEG_ADDR(Pst_pete_room_6cZ)},
    {STEEL_DOOR1, "Psteel_door1Z", OBSEG_ADDR(Psteel_door1Z)},
    {STEEL_DOOR2, "Psteel_door2Z", OBSEG_ADDR(Psteel_door2Z)},
    {STEEL_DOOR2B, "Psteel_door2bZ", OBSEG_ADDR(Psteel_door2bZ)},
    {STEEL_DOOR3, "Psteel_door3Z", OBSEG_ADDR(Psteel_door3Z)},
    {STOOL1, "Pstool1Z", OBSEG_ADDR(Pstool1Z)},
    {SWIPE_CARD2, "Pswipe_card2Z", OBSEG_ADDR(Pswipe_card2Z)},
    {SWIVEL_CHAIR1, "Pswivel_chair1Z", OBSEG_ADDR(Pswivel_chair1Z)},
    {TANK, "PtankZ", OBSEG_ADDR(PtankZ)},
    {TIGER, "PtigerZ", OBSEG_ADDR(PtigerZ)},
    {TORPEDO_RACK, "Ptorpedo_rackZ", OBSEG_ADDR(Ptorpedo_rackZ)},
    {TRAIN_DOOR2, "Ptrain_door2Z", OBSEG_ADDR(Ptrain_door2Z)},
    {TRAIN_DOOR3, "Ptrain_door3Z", OBSEG_ADDR(Ptrain_door3Z)},
    {TRAIN_DOOR, "Ptrain_doorZ", OBSEG_ADDR(Ptrain_doorZ)},
    {TRAINEXTDOOR, "PtrainextdoorZ", OBSEG_ADDR(PtrainextdoorZ)},
    {TT33MAG, "Ptt33magZ", OBSEG_ADDR(Ptt33magZ)},
    {TUNING_CONSOLE1, "Ptuning_console1Z", OBSEG_ADDR(Ptuning_console1Z)},
    {TV1, "Ptv1Z", OBSEG_ADDR(Ptv1Z)},
    {TV4SCREEN, "Ptv4screenZ", OBSEG_ADDR(Ptv4screenZ)},
    {TV_HOLDER, "Ptv_holderZ", OBSEG_ADDR(Ptv_holderZ)},
    {TVSCREEN, "PtvscreenZ", OBSEG_ADDR(PtvscreenZ)},
    {UZIMAG, "PuzimagZ", OBSEG_ADDR(PuzimagZ)},
    {VERTDOOR, "PvertdoorZ", OBSEG_ADDR(PvertdoorZ)},
    {WALLETBOND, "PwalletbondZ", OBSEG_ADDR(PwalletbondZ)},
    {WINDOW, "PwindowZ", OBSEG_ADDR(PwindowZ)},
    {WINDOW_COR11, "Pwindow_cor11Z", OBSEG_ADDR(Pwindow_cor11Z)},
    {WINDOW_LIB_LG1, "Pwindow_lib_lg1Z", OBSEG_ADDR(Pwindow_lib_lg1Z)},
    {WINDOW_LIB_SM1, "Pwindow_lib_sm1Z", OBSEG_ADDR(Pwindow_lib_sm1Z)},
    {WOOD_LG_CRATE1, "Pwood_lg_crate1Z", OBSEG_ADDR(Pwood_lg_crate1Z)},
    {WOOD_LG_CRATE2, "Pwood_lg_crate2Z", OBSEG_ADDR(Pwood_lg_crate2Z)},
    {WOOD_MD_CRATE3, "Pwood_md_crate3Z", OBSEG_ADDR(Pwood_md_crate3Z)},
    {WOOD_SM_CRATE4, "Pwood_sm_crate4Z", OBSEG_ADDR(Pwood_sm_crate4Z)},
    {WOOD_SM_CRATE5, "Pwood_sm_crate5Z", OBSEG_ADDR(Pwood_sm_crate5Z)},
    {WOOD_SM_CRATE6, "Pwood_sm_crate6Z", OBSEG_ADDR(Pwood_sm_crate6Z)},
    {WOODEN_TABLE1, "Pwooden_table1Z", OBSEG_ADDR(Pwooden_table1Z)},
    {WPPKMAG, "PwppkmagZ", OBSEG_ADDR(PwppkmagZ)},

    {BG_AME_ALL_P_STAN, "Tbg_ame_all_p_stanZ", OBSEG_ADDR(Tbg_ame_all_p_stanZ)},
    {BG_ARCH_ALL_P_STAN, "Tbg_arch_all_p_stanZ", OBSEG_ADDR(Tbg_arch_all_p_stanZ)},
    {BG_AREC_ALL_P_STAN, "Tbg_arec_all_p_stanZ", OBSEG_ADDR(Tbg_arec_all_p_stanZ)},
    {BG_ARK_ALL_P_STAN, "Tbg_ark_all_p_stanZ", OBSEG_ADDR(Tbg_ark_all_p_stanZ)},
    {BG_ASH_ALL_P_STAN, "Tbg_ash_all_p_stanZ", OBSEG_ADDR(Tbg_ash_all_p_stanZ)},
    {BG_AZT_ALL_P_STAN, "Tbg_azt_all_p_stanZ", OBSEG_ADDR(Tbg_azt_all_p_stanZ)},
    {BG_CAT_ALL_P_STAN, "Tbg_cat_all_p_stanZ", OBSEG_ADDR(Tbg_cat_all_p_stanZ)},
    {BG_CAVE_ALL_P_STAN, "Tbg_cave_all_p_stanZ", OBSEG_ADDR(Tbg_cave_all_p_stanZ)},
    {BG_CRAD_ALL_P_STAN, "Tbg_crad_all_p_stanZ", OBSEG_ADDR(Tbg_crad_all_p_stanZ)},
    {BG_CRYP_ALL_P_STAN, "Tbg_cryp_all_p_stanZ", OBSEG_ADDR(Tbg_cryp_all_p_stanZ)},
    {BG_DAM_ALL_P_STAN, "Tbg_dam_all_p_stanZ", OBSEG_ADDR(Tbg_dam_all_p_stanZ)},
    {BG_DEPO_ALL_P_STAN, "Tbg_depo_all_p_stanZ", OBSEG_ADDR(Tbg_depo_all_p_stanZ)},
    {BG_DEST_ALL_P_STAN, "Tbg_dest_all_p_stanZ", OBSEG_ADDR(Tbg_dest_all_p_stanZ)},
    {BG_DISH_ALL_P_STAN, "Tbg_dish_all_p_stanZ", OBSEG_ADDR(Tbg_dish_all_p_stanZ)},
    {BG_EAR_ALL_P_STAN, "Tbg_ear_all_p_stanZ", OBSEG_ADDR(Tbg_imp_all_p_stanZ)},
    {BG_ELD_ALL_P_STAN, "Tbg_eld_all_p_stanZ", OBSEG_ADDR(Tbg_imp_all_p_stanZ)},
    {BG_IMP_ALL_P_STAN, "Tbg_imp_all_p_stanZ", OBSEG_ADDR(Tbg_imp_all_p_stanZ)},
    {BG_JUN_ALL_P_STAN, "Tbg_jun_all_p_stanZ", OBSEG_ADDR(Tbg_jun_all_p_stanZ)},
    {BG_LEE_ALL_P_STAN, "Tbg_lee_all_p_stanZ", OBSEG_ADDR(Tbg_len_all_p_stanZ)},
    {BG_LEN_ALL_P_STAN, "Tbg_len_all_p_stanZ", OBSEG_ADDR(Tbg_len_all_p_stanZ)},
    {BG_LIP_ALL_P_STAN, "Tbg_lip_all_p_stanZ", OBSEG_ADDR(Tbg_oat_all_p_stanZ)},
    {BG_LUE_ALL_P_STAN, "Tbg_lue_all_p_stanZ", OBSEG_ADDR(Tbg_oat_all_p_stanZ)},
    {BG_OAT_ALL_P_STAN, "Tbg_oat_all_p_stanZ", OBSEG_ADDR(Tbg_oat_all_p_stanZ)},
    {BG_PAM_ALL_P_STAN, "Tbg_pam_all_p_stanZ", OBSEG_ADDR(Tbg_pete_all_p_stanZ)},
    {BG_PETE_ALL_P_STAN, "Tbg_pete_all_p_stanZ", OBSEG_ADDR(Tbg_pete_all_p_stanZ)},
    {BG_REF_ALL_P_STAN, "Tbg_ref_all_p_stanZ", OBSEG_ADDR(Tbg_ref_all_p_stanZ)},
    {BG_RIT_ALL_P_STAN, "Tbg_rit_all_p_stanZ", OBSEG_ADDR(Tbg_run_all_p_stanZ)},
    {BG_RUN_ALL_P_STAN, "Tbg_run_all_p_stanZ", OBSEG_ADDR(Tbg_run_all_p_stanZ)},
    {BG_SEV_ALL_P_STAN, "Tbg_sev_all_p_stanZ", OBSEG_ADDR(Tbg_sev_all_p_stanZ)},
    {BG_SEVB_ALL_P_STAN, "Tbg_sevb_all_p_stanZ", OBSEG_ADDR(Tbg_sevb_all_p_stanZ)},
    {BG_SEVX_ALL_P_STAN, "Tbg_sevx_all_p_stanZ", OBSEG_ADDR(Tbg_sevx_all_p_stanZ)},
    {BG_SILO_ALL_P_STAN, "Tbg_silo_all_p_stanZ", OBSEG_ADDR(Tbg_silo_all_p_stanZ)},
    {BG_STAT_ALL_P_STAN, "Tbg_stat_all_p_stanZ", OBSEG_ADDR(Tbg_stat_all_p_stanZ)},
    {BG_TRA_ALL_P_STAN, "Tbg_tra_all_p_stanZ", OBSEG_ADDR(Tbg_tra_all_p_stanZ)},
    {BG_WAX_ALL_P_STAN, "Tbg_wax_all_p_stanZ", OBSEG_ADDR(UbriefarchZ)},

    {BRIEFARCH, "UbriefarchZ", OBSEG_ADDR(UbriefarchZ)},
    {BRIEFARK, "UbriefarkZ", OBSEG_ADDR(UbriefarkZ)},
    {BRIEFAZT, "UbriefaztZ", OBSEG_ADDR(UbriefaztZ)},
    {BRIEFCAVE, "UbriefcaveZ", OBSEG_ADDR(UbriefcaveZ)},
    {BRIEFCONTROL, "UbriefcontrolZ", OBSEG_ADDR(UbriefcontrolZ)},
    {BRIEFCRAD, "UbriefcradZ", OBSEG_ADDR(UbriefcradZ)},
    {BRIEFCRYP, "UbriefcrypZ", OBSEG_ADDR(UbriefcrypZ)},
    {BRIEFDAM, "UbriefdamZ", OBSEG_ADDR(UbriefdamZ)},
    {BRIEFDEPO, "UbriefdepoZ", OBSEG_ADDR(UbriefdepoZ)},
    {BRIEFDEST, "UbriefdestZ", OBSEG_ADDR(UbriefdestZ)},
    {BRIEFJUN, "UbriefjunZ", OBSEG_ADDR(UbriefjunZ)},
    {BRIEFPETE, "UbriefpeteZ", OBSEG_ADDR(UbriefpeteZ)},
    {BRIEFRUN, "UbriefrunZ", OBSEG_ADDR(UbriefrunZ)},
    {BRIEFSEVB, "UbriefsevbZ", OBSEG_ADDR(UbriefsevbZ)},
    {BRIEFSEVBUNKER, "UbriefsevbunkerZ", OBSEG_ADDR(UbriefsevbunkerZ)},
    {BRIEFSEVX, "UbriefsevxZ", OBSEG_ADDR(UbriefsevxZ)},
    {BRIEFSEVXB, "UbriefsevxbZ", OBSEG_ADDR(UbriefsevxbZ)},
    {BRIEFSILO, "UbriefsiloZ", OBSEG_ADDR(UbriefsiloZ)},
    {BRIEFSTATUE, "UbriefstatueZ", OBSEG_ADDR(UbriefstatueZ)},
    {BRIEFTRA, "UbrieftraZ", OBSEG_ADDR(UbrieftraZ)},

    {MP_SETUPAME, "Ump_setupameZ", OBSEG_ADDR(Ump_setupameZ)},
    {MP_SETUPARCH, "Ump_setuparchZ", OBSEG_ADDR(Ump_setuparchZ)},
    {MP_SETUPARK, "Ump_setuparkZ", OBSEG_ADDR(Ump_setuparkZ)},
    {MP_SETUPASH, "Ump_setupashZ", OBSEG_ADDR(Ump_setupashZ)},
    {MP_SETUPCAVE, "Ump_setupcaveZ", OBSEG_ADDR(Ump_setupcaveZ)},
    {MP_SETUPCRAD, "Ump_setupcradZ", OBSEG_ADDR(Ump_setupcradZ)},
    {MP_SETUPCRYP, "Ump_setupcrypZ", OBSEG_ADDR(Ump_setupcrypZ)},
    {MP_SETUPDISH, "Ump_setupdishZ", OBSEG_ADDR(Ump_setupdishZ)},
    {MP_SETUPIMP, "Ump_setupimpZ", OBSEG_ADDR(Ump_setupimpZ)},
    {MP_SETUPOAT, "Ump_setupoatZ", OBSEG_ADDR(Ump_setupoatZ)},
    {MP_SETUPREF, "Ump_setuprefZ", OBSEG_ADDR(Ump_setuprefZ)},
    {MP_SETUPSEVB, "Ump_setupsevbZ", OBSEG_ADDR(Ump_setupsevbZ)},
    {MP_SETUPSTATUE, "Ump_setupstatueZ", OBSEG_ADDR(Ump_setupstatueZ)},

    {SETUPARCH, "UsetuparchZ", OBSEG_ADDR(UsetuparchZ)},
    {SETUPARK, "UsetuparkZ", OBSEG_ADDR(UsetuparkZ)},
    {SETUPAZT, "UsetupaztZ", OBSEG_ADDR(UsetupaztZ)},
    {SETUPCAVE, "UsetupcaveZ", OBSEG_ADDR(UsetupcaveZ)},
    {SETUPCONTROL, "UsetupcontrolZ", OBSEG_ADDR(UsetupcontrolZ)},
    {SETUPCRAD, "UsetupcradZ", OBSEG_ADDR(UsetupcradZ)},
    {SETUPCRYP, "UsetupcrypZ", OBSEG_ADDR(UsetupcrypZ)},
    {SETUPDAM, "UsetupdamZ", OBSEG_ADDR(UsetupdamZ)},
    {SETUPDEPO, "UsetupdepoZ", OBSEG_ADDR(UsetupdepoZ)},
    {SETUPDEST, "UsetupdestZ", OBSEG_ADDR(UsetupdestZ)},
    {SETUPJUN, "UsetupjunZ", OBSEG_ADDR(UsetupjunZ)},
    {SETUPLEN, "UsetuplenZ", OBSEG_ADDR(UsetuplenZ)},
    {SETUPPETE, "UsetuppeteZ", OBSEG_ADDR(UsetuppeteZ)},
    {SETUPRUN, "UsetuprunZ", OBSEG_ADDR(UsetuprunZ)},
    {SETUPSEVB, "UsetupsevbZ", OBSEG_ADDR(UsetupsevbZ)},
    {SETUPSEVBUNKER, "UsetupsevbunkerZ", OBSEG_ADDR(UsetupsevbunkerZ)},
    {SETUPSEVX, "UsetupsevxZ", OBSEG_ADDR(UsetupsevxZ)},
    {SETUPSEVXB, "UsetupsevxbZ", OBSEG_ADDR(UsetupsevxbZ)},
    {SETUPSILO, "UsetupsiloZ", OBSEG_ADDR(UsetupsiloZ)},
    {SETUPSTATUE, "UsetupstatueZ", OBSEG_ADDR(UsetupstatueZ)},
    {SETUPTRA, "UsetuptraZ", OBSEG_ADDR(UsetuptraZ)},

    {AMEE, "LameE", OBSEG_ADDR(LameE)},
    {AMEJ, "LameJ", OBSEG_ADDR(LameJ)},
#ifdef VERSION_EU
    {AMEP, "LameP", OBSEG_ADDR(LameP)},
#endif
    {ARCHE, "LarchE", OBSEG_ADDR(LarchE)},
    {ARCHJ, "LarchJ", OBSEG_ADDR(LarchJ)},
#ifdef VERSION_EU
    {ARCHP, "LarchP", OBSEG_ADDR(LarchP)},
#endif
    {ARECE, "LarecE", OBSEG_ADDR(LarecE)},
    {ARECJ, "LarecJ", OBSEG_ADDR(LarecJ)},
#ifdef VERSION_EU
    {ARECP, "LarecP", OBSEG_ADDR(LarecP)},
#endif
    {ARKE, "LarkE", OBSEG_ADDR(LarkE)},
    {ARKJ, "LarkJ", OBSEG_ADDR(LarkJ)},
#ifdef VERSION_EU
    {ARKP, "LarkP", OBSEG_ADDR(LarkP)},
#endif
    {ASHE, "LashE", OBSEG_ADDR(LashE)},
    {ASHJ, "LashJ", OBSEG_ADDR(LashJ)},
#ifdef VERSION_EU
    {ASHP, "LashP", OBSEG_ADDR(LashP)},
#endif
    {AZTE, "LaztE", OBSEG_ADDR(LaztE)},
    {AZTJ, "LaztJ", OBSEG_ADDR(LaztJ)},
#ifdef VERSION_EU
    {AZTP, "LaztP", OBSEG_ADDR(LaztP)},
#endif
    {CATE, "LcatE", OBSEG_ADDR(LcatE)},
    {CATJ, "LcatJ", OBSEG_ADDR(LcatJ)},
#ifdef VERSION_EU
    {CATP, "LcatP", OBSEG_ADDR(LcatP)},
#endif
    {CAVEE, "LcaveE", OBSEG_ADDR(LcaveE)},
    {CAVEJ, "LcaveJ", OBSEG_ADDR(LcaveJ)},
#ifdef VERSION_EU
    {CAVEP, "LcaveP", OBSEG_ADDR(LcaveP)},
#endif
    {CRADE, "LcradE", OBSEG_ADDR(LcradE)},
    {CRADJ, "LcradJ", OBSEG_ADDR(LcradJ)},
#ifdef VERSION_EU
    {CRADP, "LcradP", OBSEG_ADDR(LcradP)},
#endif
    {CRYPE, "LcrypE", OBSEG_ADDR(LcrypE)},
    {CRYPJ, "LcrypJ", OBSEG_ADDR(LcrypJ)},
#ifdef VERSION_EU
    {CRYPP, "LcrypP", OBSEG_ADDR(LcrypP)},
#endif
    {DAME, "LdamE", OBSEG_ADDR(LdamE)},
    {DAMJ, "LdamJ", OBSEG_ADDR(LdamJ)},
#ifdef VERSION_EU
    {DAMP, "LdamP", OBSEG_ADDR(LdamP)},
#endif
    {DEPOE, "LdepoE", OBSEG_ADDR(LdepoE)},
    {DEPOJ, "LdepoJ", OBSEG_ADDR(LdepoJ)},
#ifdef VERSION_EU
    {DEPOP, "LdepoP", OBSEG_ADDR(LdepoP)},
#endif
    {DESTE, "LdestE", OBSEG_ADDR(LdestE)},
    {DESTJ, "LdestJ", OBSEG_ADDR(LdestJ)},
#ifdef VERSION_EU
    {DESTP, "LdestP", OBSEG_ADDR(LdestP)},
#endif
    {DISHE, "LdishE", OBSEG_ADDR(LdishE)},
    {DISHJ, "LdishJ", OBSEG_ADDR(LdishJ)},
#ifdef VERSION_EU
    {DISHP, "LdishP", OBSEG_ADDR(LdishP)},
#endif
    {EARE, "LearE", OBSEG_ADDR(LearE)},
    {EARJ, "LearJ", OBSEG_ADDR(LearJ)},
#ifdef VERSION_EU
    {EARP, "LearP", OBSEG_ADDR(LearP)},
#endif
    {ELDE, "LeldE", OBSEG_ADDR(LeldE)},
    {ELDJ, "LeldJ", OBSEG_ADDR(LeldJ)},
#ifdef VERSION_EU
    {ELDP, "LeldP", OBSEG_ADDR(LeldP)},
#endif
    {GUNE, "LgunE", OBSEG_ADDR(LgunE)},
    {GUNJ, "LgunJ", OBSEG_ADDR(LgunJ)},
#ifdef VERSION_EU
    {GUNP, "LgunP", OBSEG_ADDR(LgunP)},
#endif
    {IMPE, "LimpE", OBSEG_ADDR(LimpE)},
    {IMPJ, "LimpJ", OBSEG_ADDR(LimpJ)},
#ifdef VERSION_EU
    {IMPP, "LimpP", OBSEG_ADDR(LimpP)},
#endif
    {JUNE, "LjunE", OBSEG_ADDR(LjunE)},
    {JUNJ, "LjunJ", OBSEG_ADDR(LjunJ)},
#ifdef VERSION_EU
    {JUNP, "LjunP", OBSEG_ADDR(LjunP)},
#endif
    {LEEE, "LleeE", OBSEG_ADDR(LleeE)},
    {LEEJ, "LleeJ", OBSEG_ADDR(LleeJ)},
#ifdef VERSION_EU
    {LEEP, "LleeP", OBSEG_ADDR(LleeP)},
#endif
    {LENE, "LlenE", OBSEG_ADDR(LlenE)},
    {LENJ, "LlenJ", OBSEG_ADDR(LlenJ)},
#ifdef VERSION_EU
    {LENP, "LlenP", OBSEG_ADDR(LlenP)},
#endif
    {LIPE, "LlipE", OBSEG_ADDR(LlipE)},
    {LIPJ, "LlipJ", OBSEG_ADDR(LlipJ)},
#ifdef VERSION_EU
    {LIPP, "LlipP", OBSEG_ADDR(LlipP)},
#endif
    {LUEE, "LlueE", OBSEG_ADDR(LlueE)},
    {LUEJ, "LlueJ", OBSEG_ADDR(LlueJ)},
#ifdef VERSION_EU
    {LUEP, "LlueP", OBSEG_ADDR(LlueP)},
#endif
    {MISCE, "LmiscE", OBSEG_ADDR(LmiscE)},
    {MISCJ, "LmiscJ", OBSEG_ADDR(LmiscJ)},
#ifdef VERSION_EU
    {MISCP, "LmiscP", OBSEG_ADDR(LmiscP)},
#endif
    {MPMENUE, "LmpmenuE", OBSEG_ADDR(LmpmenuE)},
    {MPMENUJ, "LmpmenuJ", OBSEG_ADDR(LmpmenuJ)},
#ifdef VERSION_EU
    {MPMENUP, "LmpmenuP", OBSEG_ADDR(LmpmenuP)},
#endif
    {MPWEAPONSE, "LmpweaponsE", OBSEG_ADDR(LmpweaponsE)},
    {MPWEAPONSJ, "LmpweaponsJ", OBSEG_ADDR(LmpweaponsJ)},
#ifdef VERSION_EU
    {MPWEAPONSP, "LmpweaponsP", OBSEG_ADDR(LmpweaponsP)},
#endif
    {OATE, "LoatE", OBSEG_ADDR(LoatE)},
    {OATJ, "LoatJ", OBSEG_ADDR(LoatJ)},
#ifdef VERSION_EU
    {OATP, "LoatP", OBSEG_ADDR(LoatP)},
#endif
    {OPTIONSE, "LoptionsE", OBSEG_ADDR(LoptionsE)},
    {OPTIONSJ, "LoptionsJ", OBSEG_ADDR(LoptionsJ)},
#ifdef VERSION_EU
    {OPTIONSP, "LoptionsP", OBSEG_ADDR(LoptionsP)},
#endif
    {PAME, "LpamE", OBSEG_ADDR(LpamE)},
    {PAMJ, "LpamJ", OBSEG_ADDR(LpamJ)},
#ifdef VERSION_EU
    {PAMP, "LpamP", OBSEG_ADDR(LpamP)},
#endif
    {PETEE, "LpeteE", OBSEG_ADDR(LpeteE)},
    {PETEJ, "LpeteJ", OBSEG_ADDR(LpeteJ)},
#ifdef VERSION_EU
    {PETEP, "LpeteP", OBSEG_ADDR(LpeteP)},
#endif
    {PROPOBJE, "LpropobjE", OBSEG_ADDR(LpropobjE)},
    {PROPOBJJ, "LpropobjJ", OBSEG_ADDR(LpropobjJ)},
#ifdef VERSION_EU
    {PROPOBJP, "LpropobjP", OBSEG_ADDR(LpropobjP)},
#endif
    {REFE, "LrefE", OBSEG_ADDR(LrefE)},
    {REFJ, "LrefJ", OBSEG_ADDR(LrefJ)},
#ifdef VERSION_EU
    {REFP, "LrefP", OBSEG_ADDR(LrefP)},
#endif
    {RITE, "LritE", OBSEG_ADDR(LritE)},
    {RITJ, "LritJ", OBSEG_ADDR(LritJ)},
#ifdef VERSION_EU
    {RITP, "LritP", OBSEG_ADDR(LritP)},
#endif
    {RUNE, "LrunE", OBSEG_ADDR(LrunE)},
    {RUNJ, "LrunJ", OBSEG_ADDR(LrunJ)},
#ifdef VERSION_EU
    {RUNP, "LrunP", OBSEG_ADDR(LrunP)},
#endif
    {SEVE, "LsevE", OBSEG_ADDR(LsevE)},
    {SEVJ, "LsevJ", OBSEG_ADDR(LsevJ)},
#ifdef VERSION_EU
    {SEVP, "LsevP", OBSEG_ADDR(LsevP)},
#endif
    {SEVBE, "LsevbE", OBSEG_ADDR(LsevbE)},
    {SEVBJ, "LsevbJ", OBSEG_ADDR(LsevbJ)},
#ifdef VERSION_EU
    {SEVBP, "LsevbP", OBSEG_ADDR(LsevbP)},
#endif
    {SEVXE, "LsevxE", OBSEG_ADDR(LsevxE)},
    {SEVXJ, "LsevxJ", OBSEG_ADDR(LsevxJ)},
#ifdef VERSION_EU
    {SEVXP, "LsevxP", OBSEG_ADDR(LsevxP)},
#endif
    {SEVXBE, "LsevxbE", OBSEG_ADDR(LsevxbE)},
    {SEVXBJ, "LsevxbJ", OBSEG_ADDR(LsevxbJ)},
#ifdef VERSION_EU
    {SEVXBP, "LsevxbP", OBSEG_ADDR(LsevxbP)},
#endif
    {SHOE, "LshoE", OBSEG_ADDR(LshoE)},
    {SHOJ, "LshoJ", OBSEG_ADDR(LshoJ)},
#ifdef VERSION_EU
    {SHOP, "LshoP", OBSEG_ADDR(LshoP)},
#endif
    {SILOE, "LsiloE", OBSEG_ADDR(LsiloE)},
    {SILOJ, "LsiloJ", OBSEG_ADDR(LsiloJ)},
#ifdef VERSION_EU
    {SILOP, "LsiloP", OBSEG_ADDR(LsiloP)},
#endif
    {STATE, "LstatE", OBSEG_ADDR(LstatE)},
    {STATJ, "LstatJ", OBSEG_ADDR(LstatJ)},
#ifdef VERSION_EU
    {STATP, "LstatP", OBSEG_ADDR(LstatP)},
#endif
    {TITLEE, "LtitleE", OBSEG_ADDR(LtitleE)},
    {TITLEJ, "LtitleJ", OBSEG_ADDR(LtitleJ)},
#ifdef VERSION_EU
    {TITLEP, "LtitleP", OBSEG_ADDR(LtitleP)},
#endif
    {TRAE, "LtraE", OBSEG_ADDR(LtraE)},
    {TRAJ, "LtraJ", OBSEG_ADDR(LtraJ)},
#ifdef VERSION_EU
    {TRAP, "LtraP", OBSEG_ADDR(LtraP)},
#endif
    {WAXE, "LwaxE", OBSEG_ADDR(LwaxE)},
    {WAXJ, "LwaxJ", OBSEG_ADDR(LwaxJ)},
#ifdef VERSION_EU
    {WAXP, "LwaxP", OBSEG_ADDR(LwaxP)},
#endif
    
    {OBENDSEG, "ob/ob_end.seg", OBSEG_ADDR(ob__ob_end_seg)},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0},
    {0}
};


